name: Deploy

on:
  # Triggers the workflow on push or pull request events but only for the master branch. 
  # But ignore a change erduced to the README.
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
  pull_request:
    branches: [ master ]
    paths-ignore:
      - README.md

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Build using Jekyll
        run: bundle exec jekyll build --trace

      - name: Add SSH key
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            mkdir -p /home/runner/.ssh
            ssh-keyscan isclab.dcc.uchile.cl >> /home/runner/.ssh/known_hosts
            echo "${{ secrets.ISCLAB_SSH_KEY }}" > /home/runner/.ssh/github_actions
            chmod 600 /home/runner/.ssh/github_actions
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
            ssh-add /home/runner/.ssh/github_actions

      - name: Deploy via SSH
        run: ./bin/deploy
